; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitc-02]
platform = espressif32
board = esp32-c3-devkitc-02
framework = arduino

build_unflags =
    -w
    -std=gnu++11
    -std=gnu++14

build_flags =
    -Iinclude
    -Iinclude/GUI
    -Wall
    -std=gnu++17

    ; ESP32-C3 can use hardware SPI, but the pins are not fixed. You can use any GPIO for SPI.
    ; See https://docs.waveshare.com/ESP32-C3-Zero for more documentation.
    ; SPI pins definitions
    -DA14=0         ; EPD_BUSY
    -DA15=1         ; EPD_RST
    -DA16=2         ; EPD_DC
    -DA17=3         ; EPD_CS
    -DEPD_SCK=4     ; EPD_SCK
    -DEPD_MOSI=5    ; EPD_MOSI

upload_speed = 921600
